// Code generated by tools/resgen from resgen.yaml. DO NOT EDIT.
// 再生成：go generate ./internal/example/resources/item（或仓库根 go generate ./...）

// Package activity 是 item 资源的 Temporal activity 实现：
// workflow 编排调用的全部副作用都在这里发生，本包再经 store 落库。
// 只有绑定型资源才有本包；其余类型资源由 handler 直调 store。
package activity

import (
	"context"
	"database/sql"
	"errors"

	"go.temporal.io/sdk/temporal"
	"go.temporal.io/sdk/worker"

	"github.com/AranjuezY/saas-template/internal/example/resources/item/port"
	"github.com/AranjuezY/saas-template/internal/example/resources/item/store"
)

// TaskQueue 是本资源 activity 任务的队列名（resgen 按 <域>.<资源>.activities 约定生成）。
// workflow 侧用它路由任务，resources-worker 只 poll 这个队列。
const TaskQueue = "example.item.activities"

// Activities 把 item 可经编排调用的写操作（未标 activity: false）封装为 Temporal activity。
type Activities struct {
	store port.Ops
}

// New 基于数据库连接构造 activity 集。
func New(database *sql.DB) *Activities {
	return &Activities{store: store.New(database)}
}

// Register 把所有 activity 注册到 worker。
func (a *Activities) Register(r worker.Registry) {
	r.RegisterActivity(a.DeleteItem)
	r.RegisterActivity(a.ApplyItemLifecycle)
}

// DeleteItem（write + lifecycle）转发到 store。幂等：目标已达成（行已删）返回成功；无拒绝条件；审计：无长期痕迹（行已删除）；workflow 事件历史与 HTTP 访问日志（均受保留期限制）
func (a *Activities) DeleteItem(ctx context.Context, in port.DeleteItemInput) error {
	return wrapActivityError(a.store.DeleteItem(ctx, in))
}

// ApplyItemLifecycle（write）转发到 store。幂等：目标已达成（同值）返回当前快照；行不存在返回 ErrNotFound（目标不可达成）；审计：stage / expires_at / updated_at 字段（可长期保留，随行存活）
func (a *Activities) ApplyItemLifecycle(ctx context.Context, in port.ApplyItemLifecycleInput) (port.ApplyItemLifecycleOutput, error) {
	out, err := a.store.ApplyItemLifecycle(ctx, in)
	return out, wrapActivityError(err)
}

// wrapActivityError 把业务错误标记为不可重试并保留用户可读消息；
// 其余错误原样返回，交给重试策略处理。
//
// 错误信封直接用 temporal SDK 的 ApplicationError——它跨进程传输后
// 仍是 *temporal.ApplicationError，handler 侧 errors.As 即可取回消息。
func wrapActivityError(err error) error {
	if err == nil {
		return nil
	}
	var ve port.ValidationError
	switch {
	case errors.As(err, &ve):
		return temporal.NewNonRetryableApplicationError(ve.Message, "validation", err)
	case errors.Is(err, port.ErrNotFound):
		return temporal.NewNonRetryableApplicationError("该记录已不存在", "not_found", err)
	default:
		return err
	}
}
