// Code generated by tools/resgen from resgen.yaml. DO NOT EDIT.
// 再生成：go generate ./internal/example/resources/item（或仓库根 go generate ./...）

// Package activity 是 item 资源的 Temporal activity 实现：
// workflow 编排调用的全部副作用都在这里发生，本包再经 store 落库。
// 只有绑定型资源才有本包；其余类型资源由 handler 直调 store。
package activity

import (
	"context"
	"database/sql"
	"errors"

	"go.temporal.io/sdk/temporal"
	"go.temporal.io/sdk/worker"

	"github.com/AranjuezY/saas-template/internal/example/resources/item/port"
	"github.com/AranjuezY/saas-template/internal/example/resources/item/store"
)

// TaskQueue 是本资源 activity 任务的队列名（resgen 按 <域>.<资源>.activities 约定生成）。
// workflow 侧用它路由任务，resources-worker 只 poll 这个队列。
const TaskQueue = "example.item.activities"

// Activities 把 item 的全部写操作封装为 Temporal activity。
type Activities struct {
	store port.Ops
}

// New 基于数据库连接构造 activity 集。
func New(database *sql.DB) *Activities {
	return &Activities{store: store.New(database)}
}

// Register 把所有 activity 注册到 worker。
func (a *Activities) Register(r worker.Registry) {
	r.RegisterActivity(a.CreateItem)
	r.RegisterActivity(a.UpdateItemStage)
	r.RegisterActivity(a.DeleteItem)
}

// CreateItem（write + lifecycle）转发到 store。幂等：ExecuteWorkflow 是持久化启动，worker 恢复后补执行，不重复发起；落库本身产生新 ID，重复执行表现为新增而非覆盖；审计：created_at / updated_at 字段 + workflow 执行历史
func (a *Activities) CreateItem(ctx context.Context, in port.CreateItemInput) (port.CreateItemOutput, error) {
	out, err := a.store.CreateItem(ctx, in)
	return out, wrapActivityError(err)
}

// UpdateItemStage（write）转发到 store。幂等：UPDATE 到相同值幂等；目标行不存在返回 ErrNotFound，重试不重复生效；审计：updated_at 字段
func (a *Activities) UpdateItemStage(ctx context.Context, in port.UpdateItemStageInput) (port.UpdateItemStageOutput, error) {
	out, err := a.store.UpdateItemStage(ctx, in)
	return out, wrapActivityError(err)
}

// DeleteItem（write + lifecycle）转发到 store。幂等：二次删除返回 ErrNotFound；先取消后删除的顺序保证不留孤儿 Running 实例；审计：workflow 执行历史 + RowsAffected 检查
func (a *Activities) DeleteItem(ctx context.Context, in port.DeleteItemInput) error {
	return wrapActivityError(a.store.DeleteItem(ctx, in))
}

// wrapActivityError 把业务错误标记为不可重试并保留用户可读消息；
// 其余错误原样返回，交给重试策略处理。
//
// 错误信封直接用 temporal SDK 的 ApplicationError——它跨进程传输后
// 仍是 *temporal.ApplicationError，handler 侧 errors.As 即可取回消息。
func wrapActivityError(err error) error {
	if err == nil {
		return nil
	}
	var ve port.ValidationError
	switch {
	case errors.As(err, &ve):
		return temporal.NewNonRetryableApplicationError(ve.Message, "validation", err)
	case errors.Is(err, port.ErrNotFound):
		return temporal.NewNonRetryableApplicationError("该记录已不存在", "not_found", err)
	default:
		return err
	}
}
