// Code generated by tools/resgen from resgen.yaml. DO NOT EDIT.
// 再生成：go generate ./internal/example/resources/item（或仓库根 go generate ./...）

package port

import (
	"context"
)

// 操作类别（三类，不再细分；可叠加：如"新增"既是写入也启动生命周期）。
type OpKind string

const (
	OpWrite      OpKind = "write"      // 写入事实（资源唯一写入点之内）
	OpLifecycle  OpKind = "lifecycle"  // 启动、推进或结束流程
	OpSideEffect OpKind = "sideeffect" // 外部副作用（邮件 / 通知 / 第三方系统）
)

// Operation 是资源操作清单的一项。
type Operation struct {
	Name           string   // 操作名，与对外入口同名
	Kinds          []OpKind // 类别
	WorkflowImpact string   // 对 workflow 的影响
	Idempotency    string   // 幂等规则：重试不得重复生效
	Audit          string   // 审计规则
}

// Operations 是 item 资源的操作清单（由规格 resgen.yaml 生成）。
// 写入、生命周期与副作用类操作必须登记且登记先于实现（AGENTS.md 不变量 6）；
// 只读操作不必登记。handler 侧有守卫测试：编排入口不登记即失败。
var Operations = []Operation{
	{
		Name:           "CreateItem",
		Kinds:          []OpKind{OpWrite},
		WorkflowImpact: "无影响：draft 无流程实例",
		Idempotency:    "无去重键，重复执行表现为新增；调用方不得对同一意图重试",
		Audit:          "items 行的 created_at / updated_at（可长期保留，随行存活）",
	},
	{
		Name:           "ActivateItem",
		Kinds:          []OpKind{OpLifecycle},
		WorkflowImpact: "拉起 item/{id} 实例（若未运行），起 DefaultValidity 到期定时器",
		Idempotency:    "目标已达成（已 active）返回当前快照；无拒绝条件",
		Audit:          "expires_at / updated_at 字段（可长期保留，随行存活）；workflow 事件历史（受保留期限制）",
	},
	{
		Name:           "RenewItem",
		Kinds:          []OpKind{OpLifecycle},
		WorkflowImpact: "将实例的到期定时器顺延一个 DefaultValidity",
		Idempotency:    "冲突则拒绝：非 active，或已到期（自动归档进行中）；同输入重放按 Update ID 去重，状态变化后的新意图各自顺延",
		Audit:          "expires_at / updated_at 字段（可长期保留，随行存活）；workflow 事件历史（受保留期限制）",
	},
	{
		Name:           "ArchiveItem",
		Kinds:          []OpKind{OpLifecycle},
		WorkflowImpact: "取消实例的到期定时器并结束实例",
		Idempotency:    "目标已达成（已归档）时实例已关闭，重复请求在传输层被拒；运行中无拒绝条件",
		Audit:          "stage / updated_at 字段（可长期保留，随行存活）；workflow 事件历史（受保留期限制）",
	},
	{
		Name:           "DeleteItem",
		Kinds:          []OpKind{OpWrite, OpLifecycle},
		WorkflowImpact: "active：结束实例（流程内删行）；draft / archived：无实例可影响",
		Idempotency:    "目标已达成（行已删）返回成功；无拒绝条件",
		Audit:          "无长期痕迹（行已删除）；workflow 事件历史与 HTTP 访问日志（均受保留期限制）",
	},
	{
		Name:           "ApplyItemLifecycle",
		Kinds:          []OpKind{OpWrite},
		WorkflowImpact: "无影响：仅由实例自身调用",
		Idempotency:    "目标已达成（同值）返回当前快照；行不存在返回 ErrNotFound（目标不可达成）",
		Audit:          "stage / expires_at / updated_at 字段（可长期保留，随行存活）",
	},
}

// CreateItemInput 是 CreateItem 的输入（快照值，不带行为、不连数据库）。
type CreateItemInput struct {
	Item Item `json:"item"`
}

// CreateItemOutput 是 CreateItem 的输出。
type CreateItemOutput struct {
	Item Item `json:"item"`
}

// ActivateItemInput 是 ActivateItem 的输入（快照值，不带行为、不连数据库）。
type ActivateItemInput struct {
	ID               int64  `json:"id"`
	CurrentStage     string `json:"current_stage"`
	CurrentExpiresAt string `json:"current_expires_at"`
}

// ActivateItemOutput 是 ActivateItem 的输出。
type ActivateItemOutput struct {
	Item Item `json:"item"`
}

// RenewItemInput 是 RenewItem 的输入（快照值，不带行为、不连数据库）。
type RenewItemInput struct {
	ID               int64  `json:"id"`
	CurrentStage     string `json:"current_stage"`
	CurrentExpiresAt string `json:"current_expires_at"`
}

// RenewItemOutput 是 RenewItem 的输出。
type RenewItemOutput struct {
	Item Item `json:"item"`
}

// ArchiveItemInput 是 ArchiveItem 的输入（快照值，不带行为、不连数据库）。
type ArchiveItemInput struct {
	ID               int64  `json:"id"`
	CurrentStage     string `json:"current_stage"`
	CurrentExpiresAt string `json:"current_expires_at"`
}

// ArchiveItemOutput 是 ArchiveItem 的输出。
type ArchiveItemOutput struct {
	Item Item `json:"item"`
}

// DeleteItemInput 是 DeleteItem 的输入（快照值，不带行为、不连数据库）。
type DeleteItemInput struct {
	ID     int64  `json:"id"`
	Reason string `json:"reason"`
}

// ApplyItemLifecycleInput 是 ApplyItemLifecycle 的输入（快照值，不带行为、不连数据库）。
type ApplyItemLifecycleInput struct {
	ID        int64  `json:"id"`
	Stage     string `json:"stage"`
	ExpiresAt string `json:"expires_at"`
}

// ApplyItemLifecycleOutput 是 ApplyItemLifecycle 的输出。
type ApplyItemLifecycleOutput struct {
	Item Item `json:"item"`
}

// Ops 是 item 的操作接口：规格登记的 write / sideeffect 操作与约定读操作。
// 实现于 store 包的未导出类型，构造函数返回本接口——每个可变事实只有一个写入点。
type Ops interface {
	// CreateItem（write）。幂等：无去重键，重复执行表现为新增；调用方不得对同一意图重试
	CreateItem(ctx context.Context, in CreateItemInput) (CreateItemOutput, error)
	// DeleteItem（write + lifecycle）。幂等：目标已达成（行已删）返回成功；无拒绝条件
	DeleteItem(ctx context.Context, in DeleteItemInput) error
	// ApplyItemLifecycle（write）。幂等：目标已达成（同值）返回当前快照；行不存在返回 ErrNotFound（目标不可达成）
	ApplyItemLifecycle(ctx context.Context, in ApplyItemLifecycleInput) (ApplyItemLifecycleOutput, error)

	// List 约定读操作：全量查询（LIMIT 内按需调整分页）。
	List(ctx context.Context) ([]Item, error)
	// Get 约定读操作：按 ID 查询，不存在返回 ErrNotFound。
	Get(ctx context.Context, id int64) (Item, error)
}
