// Code generated by tools/resgen from resgen.yaml. DO NOT EDIT.
// 再生成：go generate ./internal/example/resources/item（或仓库根 go generate ./...）

package port

import (
	"context"
)

// 操作类别（三类，不再细分；可叠加：如"新增"既是写入也启动生命周期）。
type OpKind string

const (
	OpWrite      OpKind = "write"      // 写入事实（资源唯一写入点之内）
	OpLifecycle  OpKind = "lifecycle"  // 启动、推进或结束流程
	OpSideEffect OpKind = "sideeffect" // 外部副作用（邮件 / 通知 / 第三方系统）
)

// Operation 是资源操作清单的一项。
type Operation struct {
	Name           string   // 操作名，与对外入口同名
	Kinds          []OpKind // 类别
	WorkflowImpact string   // 对 workflow 的影响
	Idempotency    string   // 幂等规则：重试不得重复生效
	Audit          string   // 审计规则
}

// Operations 是 item 资源的操作清单（由规格 resgen.yaml 生成）。
// 写入、生命周期与副作用类操作必须登记且登记先于实现（AGENTS.md 不变量 6）；
// 只读操作不必登记。handler 侧有守卫测试：编排入口不登记即失败。
var Operations = []Operation{
	{
		Name:           "CreateItem",
		Kinds:          []OpKind{OpWrite, OpLifecycle},
		WorkflowImpact: "落库后以 item/{id} 拉起生命周期流程（Abandon 子流程），只等启动确认",
		Idempotency:    "ExecuteWorkflow 是持久化启动，worker 恢复后补执行，不重复发起；落库本身产生新 ID，重复执行表现为新增而非覆盖",
		Audit:          "created_at / updated_at 字段 + workflow 执行历史",
	},
	{
		Name:           "AdvanceStage",
		Kinds:          []OpKind{OpLifecycle},
		WorkflowImpact: "向 item/{id} 发 activate / archive 信号；阶段只能由流程内的 activity 落库",
		Idempotency:    "信号重复送达安全：目标阶段与当前一致时 UPDATE 写相同值，不产生新事实",
		Audit:          "workflow 事件历史 + updated_at",
	},
	{
		Name:           "UpdateItemStage",
		Kinds:          []OpKind{OpWrite},
		WorkflowImpact: "仅被生命周期流程的信号分支调用，是条目阶段唯一写入口；页面不得直接改",
		Idempotency:    "UPDATE 到相同值幂等；目标行不存在返回 ErrNotFound，重试不重复生效",
		Audit:          "updated_at 字段",
	},
	{
		Name:           "DeleteItem",
		Kinds:          []OpKind{OpWrite, OpLifecycle},
		WorkflowImpact: "删除的合规形态：CancelItemWorkflow 先请求取消 item/{id} 流程再删记录，全程留审计轨迹",
		Idempotency:    "二次删除返回 ErrNotFound；先取消后删除的顺序保证不留孤儿 Running 实例",
		Audit:          "workflow 执行历史 + RowsAffected 检查",
	},
}

// CreateItemInput 是 CreateItem 的输入（快照值，不带行为、不连数据库）。
type CreateItemInput struct {
	Item Item `json:"item"`
}

// CreateItemOutput 是 CreateItem 的输出。
type CreateItemOutput struct {
	Item Item `json:"item"`
}

// AdvanceStageInput 是 AdvanceStage 的输入（快照值，不带行为、不连数据库）。
type AdvanceStageInput struct {
	ID           int64  `json:"id"`
	CurrentStage string `json:"current_stage"`
	NextStage    string `json:"next_stage"`
}

// UpdateItemStageInput 是 UpdateItemStage 的输入（快照值，不带行为、不连数据库）。
type UpdateItemStageInput struct {
	ID    int64  `json:"id"`
	Stage string `json:"stage"`
}

// UpdateItemStageOutput 是 UpdateItemStage 的输出。
type UpdateItemStageOutput struct {
	Item Item `json:"item"`
}

// DeleteItemInput 是 DeleteItem 的输入（快照值，不带行为、不连数据库）。
type DeleteItemInput struct {
	ID     int64  `json:"id"`
	Reason string `json:"reason"`
}

// Ops 是 item 的操作接口：规格登记的 write / sideeffect 操作与约定读操作。
// 实现于 store 包的未导出类型，构造函数返回本接口——每个可变事实只有一个写入点。
type Ops interface {
	// CreateItem（write + lifecycle）。幂等：ExecuteWorkflow 是持久化启动，worker 恢复后补执行，不重复发起；落库本身产生新 ID，重复执行表现为新增而非覆盖
	CreateItem(ctx context.Context, in CreateItemInput) (CreateItemOutput, error)
	// UpdateItemStage（write）。幂等：UPDATE 到相同值幂等；目标行不存在返回 ErrNotFound，重试不重复生效
	UpdateItemStage(ctx context.Context, in UpdateItemStageInput) (UpdateItemStageOutput, error)
	// DeleteItem（write + lifecycle）。幂等：二次删除返回 ErrNotFound；先取消后删除的顺序保证不留孤儿 Running 实例
	DeleteItem(ctx context.Context, in DeleteItemInput) error

	// List 约定读操作：全量查询（LIMIT 内按需调整分页）。
	List(ctx context.Context) ([]Item, error)
	// Get 约定读操作：按 ID 查询，不存在返回 ErrNotFound。
	Get(ctx context.Context, id int64) (Item, error)
}
