// Code generated by tools/resgen from resgen.yaml. DO NOT EDIT.
// 再生成：go generate ./internal/example/resources/item（或仓库根 go generate ./...）

package handler

import (
	"context"

	"github.com/AranjuezY/saas-template/internal/example/resources/item/port"
)

// Orchestrator 是 item 对编排层的全部需求（消费者侧接口，由规格生成）。
// 生产实现是域 workflow 客户端（按 contract 契约按名调用，不 import workflow 定义）；
// 测试用假实现直写 store，handler 测试因此无需 Temporal Server。
type Orchestrator interface {
	// ActivateItem（lifecycle）。拉起 item/{id} 实例（若未运行），起 DefaultValidity 到期定时器
	ActivateItem(ctx context.Context, in port.ActivateItemInput) (port.ActivateItemOutput, error)
	// RenewItem（lifecycle）。将实例的到期定时器顺延一个 DefaultValidity
	RenewItem(ctx context.Context, in port.RenewItemInput) (port.RenewItemOutput, error)
	// ArchiveItem（lifecycle）。取消实例的到期定时器并结束实例
	ArchiveItem(ctx context.Context, in port.ArchiveItemInput) (port.ArchiveItemOutput, error)
	// DeleteItem（write + lifecycle）。active：结束实例（流程内删行）；draft / archived：无实例可影响
	DeleteItem(ctx context.Context, in port.DeleteItemInput) error
}
