// Code generated by tools/resgen from resgen.yaml. DO NOT EDIT.
// 再生成：go generate ./internal/example/resources/item（或仓库根 go generate ./...）

package handler

import (
	"context"

	"github.com/AranjuezY/saas-template/internal/example/resources/item/port"
)

// Orchestrator 是 item 对编排层的全部需求（消费者侧接口，由规格生成）。
// 生产实现是域 workflow 客户端（按 contract 契约按名调用，不 import workflow 定义）；
// 测试用假实现直写 store，handler 测试因此无需 Temporal Server。
type Orchestrator interface {
	// CreateItem（write + lifecycle）。落库后以 item/{id} 拉起生命周期流程（Abandon 子流程），只等启动确认
	CreateItem(ctx context.Context, in port.CreateItemInput) (port.CreateItemOutput, error)
	// AdvanceStage（lifecycle）。向 item/{id} 发 activate / archive 信号；阶段只能由流程内的 activity 落库
	AdvanceStage(ctx context.Context, in port.AdvanceStageInput) error
	// DeleteItem（write + lifecycle）。删除的合规形态：CancelItemWorkflow 先请求取消 item/{id} 流程再删记录，全程留审计轨迹
	DeleteItem(ctx context.Context, in port.DeleteItemInput) error
}
